package au.net.hal9000.heisenberg.ai;

import au.net.hal9000.heisenberg.ai.api.ModelState;
import au.net.hal9000.heisenberg.units.Position;

/**
 * A very simple model state. It holds two positions, the agent and the goal.
 * 
 * @author bruins
 * @version $Revision: 1.0 $
 */
public class ModelStateImpl implements ModelState, Cloneable {

    /** The agent moving to goal. */
    private Position agentPosition;
    /** Where the agent wants to be. */
    private Position goalPosition;

    /**
     * Constructor.
     * 
     * @param agentPosition
     *            agent position.
     * @param goalPosition
     *            goal position.
     */
    public ModelStateImpl(Position agentPosition, Position goalPosition) {
        this.agentPosition = agentPosition;
        this.goalPosition = goalPosition;
    }

    /**
     * Constructor.
     * @param modelState to copy.
     */
    public ModelStateImpl(ModelStateImpl modelState) {
        this(new Position(modelState.getAgentPosition()), new Position(
                modelState.getGoalPosition()));
    }

    /** {@inheritDoc} */
    @Override
    public Position getAgentPosition() {
        return agentPosition;
    }

    /** {@inheritDoc} */
    @Override
    public void setAgentPosition(Position position3d) {
        agentPosition = position3d;
    }

    /** {@inheritDoc} */
    @Override
    public Position getGoalPosition() {
        return goalPosition;
    }

    /** {@inheritDoc} */
    @Override
    public void setGoalPosition(Position position3d) {
        goalPosition = position3d;
    }

    // Autogenerated
    /**
     * Method hashCode.
     * 
     * @return int
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((null == agentPosition) ? 0 : agentPosition.hashCode());
        result = prime * result
                + ((null == goalPosition) ? 0 : goalPosition.hashCode());
        return result;
    }

    // Autogenerated
    /**
     * Method equals.
     * 
     * @param obj
     *            Object
     * @return boolean
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (null == obj) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        ModelStateImpl other = (ModelStateImpl) obj;
        if (null == agentPosition) {
            if (null != other.agentPosition) {
                return false;
            }
        } else if (!agentPosition.equals(other.agentPosition)) {
            return false;
        }
        if (null == goalPosition) {
            if (null != other.goalPosition) {
                return false;
            }
        } else if (!goalPosition.equals(other.goalPosition)) {
            return false;
        }
        return true;
    }

    /**
     * Method toString.
     * 
     * @return String
     */
    @Override
    public String toString() {
        return "[agent=" + agentPosition + ", goal=" + goalPosition + "]";
    }

    @Override
    public void agentPositionChange(Position delta) {
        agentPosition.addLocal(delta);
    }

}
